# Be sure to change these!
base_url = "//xxkeith.com/"
title = "XXXMRG's blog"

# Sass compilation is required
compile_sass = true

default_language = "zh-CN"

# Optional: enable tags
taxonomies = [
    {name = "tags"}
]

theme = "archie-zola"

[markdown]
# Code highlighting
highlight_code = true
highlight_theme = "OneHalfLight"


[extra]
# Put all your custom variables here

subtitle = "弃恶离善执中道，不以形物役吾心"

# control dark mode: auto | dark | toggle
mode = "toggle"

# interal CDN resource
useCDN = false

favicon = "/icon/favicon.png"

copyright = "keith"



[[extra.translations.zh-CN]]
show_more = "Read more ⟶"
previous_page = "← Previous"
next_page = "Next →"
posted_on = "on "
posted_by = "Published by"
read_time = "minute read"
all_tags = "All tags"
menus = [
    { name = "All posts", url = "/posts", weight = 2 },
    { name = "Translation", url = "/translation", weight = 2 },
    { name = "Tags", url = "/tags", weight = 4 },
]

# config social icon info in the footer
[[extra.social]]
icon = "github"
name = "GitHub"
url = "https://github.com/XXXMrG"
