# Be sure to change these!
base_url = "//xkeith-tech.vercel.app/"
title = "XXXMRG's blog"

# Sass compilation is required
compile_sass = true

# Optional: enable tags
taxonomies = [
    {name = "tags"}
]

default_language = "zh-CN"

theme = "archie-zola"

[markdown]
# Code highlighting
highlight_code = true
highlight_theme = "OneHalfLight"


[extra]
# Put all your custom variables here

subtitle = "弃恶离善执中道，不以形物役吾心"

# control dark mode: auto | dark | toggle
mode = "toggle"

# interal CDN resource
useCDN = false

favicon = "/icon/favicon.png"

copyright = "keith"


[[extra.menu]]
name = "All posts"
url = "/posts"
weight = 2


[[extra.menu]]
name = "Tags"
url = "/tags"
weight = 4

[[extra.social]]
icon = "github"
name = "GitHub"
url = "https://github.com/XXXMrG"
